# based on https://github.com/predictionmachine/pm-gh-actions/blob/main/pyproject.toml
# pm-version 0.1.2

[tool.black]
# see https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-format
# your black config goes here

[tool.coverage.run]
# see https://coverage.readthedocs.io/en/latest/config.html
omit = ["tests/*"]

[tool.interrogate]
# see https://interrogate.readthedocs.io/en/latest/#configuration
ignore-init-method = true
ignore-init-module = true
ignore-magic = true
fail-under = 100
exclude = ["out", "tests"]
verbose = 1
quiet = false
color = true
ignore-nested-functions = true

[tool.pytest.ini_options]
# see https://docs.pytest.org/en/6.2.x/customize.html#pyproject-toml
addopts = "--strict-markers -vv"
markers = [
    'integration: integration tests'
]
doctest_optionflags = ['NORMALIZE_WHITESPACE', 'IGNORE_EXCEPTION_DETAIL']
log_format = '%(asctime)s.%(msecs)03d [%(levelname)s] %(filename)12s:%(lineno)d fn=%(funcName)s	%(message)s'
log_date_format = '%Y-%m-%dT%H:%M:%S'
log_level = 'INFO'
log_cli_level = 'INFO'
filterwarnings = [
    'ignore:"@coroutine" decorator:DeprecationWarning',
    'ignore:The loop argument:DeprecationWarning'
]
